services:
  proxy:
    build:
      ./proxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - geo
    environment:
      APP_VERSION: 1.0.0
      HOST: proxy
      PORT: 8080
      LOG_LEVEL: debug
      GEO_PORT: 1000
      GEO_HOST: geo


  geo:
    build:
      ./geo
    ports:
      - 1000:1000
    depends_on:
      - redis
    restart: always
    environment:
      APP_VERSION: 1.2.0
      HOST: geo
      PORT: 1000
      METRICS_PORT: 1001
      DADATA_API_KEY: ${DADATA_API_KEY}
      DADATA_SECRET_KEY: ${DADATA_SECRET_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis:latest
    restart: always

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#
#  grafana:
#    image: grafana/grafana:latest
#    ports:
#      - 3000:3000
#    environment:
#      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
#      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
#    volumes:
#      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
#      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
#      - ./grafana/dashboards:/etc/dashboards