version: 3

silent: true
dotenv: ['.env']

includes:
  geo: ./geo
  proxy: ./proxy

tasks:
  default:
    desc: Build the application and generate Swagger docs
    cmds:
      - task: proxy:swagger:generate
      - task: build

  build: docker compose up --build --force-recreate

  clear_logs: echo '' > .log

  dump_logs: docker compose logs &> .log

