basePath: /
host: localhost:8080
info:
  contact: {}
  description: Geoservice API
  title: Microservice Geoservice
  version: 2.0.0
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
