global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8888']