version: 3

silent: true

vars:
  DIR: '{{.DIR | default .TASKFILE_DIR}}'
  NAME: '{{.NAME | default "proxy"}}'
  VERSION: '{{.VERSION | default "v1"}}'
  PACKAGE_NAME: '{{.NAME}}_{{.VERSION}}'
  SERVICE_NAME: '{{.NAME}}'

env:
  GOBIN: '{{.DIR}}/bin'

tasks:
  swagger:generate:
    dir: '{{.DIR}}'
    cmds:
      - cmd: swag init --parseDependency -g ./cmd/app/main.go