// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: geo.proto

package geo_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeoProviderV1_AddressSearch_FullMethodName = "/geo_v1.GeoProviderV1/AddressSearch"
	GeoProviderV1_GeoCode_FullMethodName       = "/geo_v1.GeoProviderV1/GeoCode"
)

// GeoProviderV1Client is the client API for GeoProviderV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeoProviderV1Client interface {
	AddressSearch(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*AddressesResponse, error)
	GeoCode(ctx context.Context, in *GeoRequest, opts ...grpc.CallOption) (*AddressesResponse, error)
}

type geoProviderV1Client struct {
	cc grpc.ClientConnInterface
}

func NewGeoProviderV1Client(cc grpc.ClientConnInterface) GeoProviderV1Client {
	return &geoProviderV1Client{cc}
}

func (c *geoProviderV1Client) AddressSearch(ctx context.Context, in *AddressRequest, opts ...grpc.CallOption) (*AddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressesResponse)
	err := c.cc.Invoke(ctx, GeoProviderV1_AddressSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoProviderV1Client) GeoCode(ctx context.Context, in *GeoRequest, opts ...grpc.CallOption) (*AddressesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddressesResponse)
	err := c.cc.Invoke(ctx, GeoProviderV1_GeoCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoProviderV1Server is the server API for GeoProviderV1 service.
// All implementations must embed UnimplementedGeoProviderV1Server
// for forward compatibility.
type GeoProviderV1Server interface {
	AddressSearch(context.Context, *AddressRequest) (*AddressesResponse, error)
	GeoCode(context.Context, *GeoRequest) (*AddressesResponse, error)
	mustEmbedUnimplementedGeoProviderV1Server()
}

// UnimplementedGeoProviderV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeoProviderV1Server struct{}

func (UnimplementedGeoProviderV1Server) AddressSearch(context.Context, *AddressRequest) (*AddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddressSearch not implemented")
}
func (UnimplementedGeoProviderV1Server) GeoCode(context.Context, *GeoRequest) (*AddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeoCode not implemented")
}
func (UnimplementedGeoProviderV1Server) mustEmbedUnimplementedGeoProviderV1Server() {}
func (UnimplementedGeoProviderV1Server) testEmbeddedByValue()                       {}

// UnsafeGeoProviderV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoProviderV1Server will
// result in compilation errors.
type UnsafeGeoProviderV1Server interface {
	mustEmbedUnimplementedGeoProviderV1Server()
}

func RegisterGeoProviderV1Server(s grpc.ServiceRegistrar, srv GeoProviderV1Server) {
	// If the following call pancis, it indicates UnimplementedGeoProviderV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeoProviderV1_ServiceDesc, srv)
}

func _GeoProviderV1_AddressSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoProviderV1Server).AddressSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoProviderV1_AddressSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoProviderV1Server).AddressSearch(ctx, req.(*AddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoProviderV1_GeoCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoProviderV1Server).GeoCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeoProviderV1_GeoCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoProviderV1Server).GeoCode(ctx, req.(*GeoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeoProviderV1_ServiceDesc is the grpc.ServiceDesc for GeoProviderV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeoProviderV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geo_v1.GeoProviderV1",
	HandlerType: (*GeoProviderV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddressSearch",
			Handler:    _GeoProviderV1_AddressSearch_Handler,
		},
		{
			MethodName: "GeoCode",
			Handler:    _GeoProviderV1_GeoCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "geo.proto",
}
